version: '3.8'
services:
  frontend:
    container_name: citylink-frontend
    build:
      context: .
      args:
        - VITE_API_HOST=${VITE_API_HOST}
        - VITE_USE_MOCK=${VITE_USE_MOCK}
    ports:
      - 80:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
