version: "3.8"
services:
  frontend:
    container_name: citylink-frontend
    build:
      context: ./frontend
      args:
        - VITE_USE_MOCK=true # true - включает моковый сервер. Можно потыкать фронтенд без реального бэкенда
        - VITE_API_HOST=http://localhost:8080/api #адрес реального бэкенда
    ports:
      - 80:8080
